### ISSUE TITLE
Tensorflow 2.1.3 requires numphy < 1.9.0 which conflicts with horovod requierments. 

### ISSUE THREAD

**Issue by manospavlidakis** [kaust-vislab/horovod-gpu-data-science-project#1]
The environment.yml with Tensorflow 2.1.3 (tensorflow-gpu==2.1.*) does not work. This happens because TF requires numphy<1.9.0 and horovod installs 1.9.5. Even if I add in the yaml file the required numphy horovod uninstalls it!

**Comment by Bobyuan1015** [comment]
have you solved it?

**Comment by davidrpugh** [comment]
If there is a dependency conflict, then that issue should be opened with [Horovod ](https://github.com/horovod/horovod
) directly. I am only maintaining a template repo for Horovod including the most current versions of the core frameworks.
